version: '3.8'

services:
  marz-node-bot:
    build: .
    container_name: marz-node-bot
    restart: unless-stopped
    
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    
    volumes:
      # Mount data directory for persistent database storage
      - ./data:/app/data
      # Mount logs directory (optional)
      - ./logs:/app/logs
      # Mount .env file
      - ./.env:/app/.env:ro
    
    networks:
      - marz-node-network
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    # Resource limits (optional - adjust based on your needs)
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  marz-node-network:
    driver: bridge
    name: marz-node-network

volumes:
  marz-node-data:
    driver: local
    name: marz-node-data
