version: '3.8'

services:
  marzban-node-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marzban-node-bot
    restart: unless-stopped
    
    # Environment variables
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_IDS=${ADMIN_IDS}
      - DATABASE_PATH=/app/data/bot_database.db
      - DEFAULT_LANGUAGE=${DEFAULT_LANGUAGE:-fa}
      - SSH_TIMEOUT=${SSH_TIMEOUT:-30}
      - API_TIMEOUT=${API_TIMEOUT:-30}
      - DEFAULT_NODE_PORT=${DEFAULT_NODE_PORT:-62050}
      - DEFAULT_API_PORT=${DEFAULT_API_PORT:-62051}
    
    # Volumes for data persistence
    volumes:
      - bot_data:/app/data
      - ./logs:/app/logs
      - ~/.ssh:/home/botuser/.ssh:ro  # SSH keys for node management
    
    # Network configuration
    networks:
      - marzban_network
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Security options
    security_opt:
      - no-new-privileges:true
    
    # Read-only root filesystem (except for writable volumes)
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import sqlite3; sqlite3.connect('/app/data/bot_database.db').close()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Optional: Monitoring service
  bot-monitor:
    image: prom/node-exporter:latest
    container_name: bot-monitor
    restart: unless-stopped
    ports:
      - "9100:9100"
    networks:
      - marzban_network
    profiles:
      - monitoring

  # Optional: Log aggregation
  log-collector:
    image: fluent/fluent-bit:latest
    container_name: log-collector
    restart: unless-stopped
    volumes:
      - ./logs:/fluent-bit/logs:ro
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
    networks:
      - marzban_network
    profiles:
      - logging

# Named volumes for data persistence
volumes:
  bot_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data

# Network configuration
networks:
  marzban_network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1500
