
"""
Multilingual text content for the bot
"""

TEXTS = {
    'en': {
        # Start and language selection
        'welcome': "🎉 Welcome to Marzban Node Management Bot! 🚀\n\nThis bot helps you easily install and manage Marzban nodes through a user-friendly interface.",
        'select_language': "🌍 Please select your preferred language for communication:",
        'language_selected': "✅ Language successfully set to English.",

        # Main menu
        'main_menu': "🏠 Main Menu",
        'main_menu_desc': "Please select the operation you would like to perform:",
        'add_panel': "➕ Add New Panel",
        'manage_nodes': "🔧 Manage Nodes",
        'admin_panel': "👑 Admin Panel",
        'backup_data': "💾 Backup Management",
        'statistics': "📊 View Statistics",

        # Panel management
        'panel_type': "Please select the type of panel you want to add:",
        'marzban_panel': "🚀 Marzban Panel",
        'enter_panel_url': "Please enter your panel URL (without /dashboard or other paths):\n\nExample: https://your-domain.com",
        'enter_username': "Please enter the admin username (ensure it has sudo privileges):",
        'enter_password': "Please enter the admin password:",
        'enter_panel_name': "Please enter a name for this panel for easy identification:",
        'panel_saved': "✅ Panel has been successfully saved and is ready for use.",
        'panel_connection_failed': "❌ Failed to connect to the panel. Please verify your credentials and try again.",

        # Node management
        'select_panel': "Please select the panel you want to work with:",
        'no_panels': "⚠️ No panels have been added yet. Please add a panel first to continue.",
        'node_management': "🔧 Node Management Center",
        'list_nodes': "📋 List All Nodes",
        'get_node_info': "ℹ️ View Node Details",
        'add_new_node': "➕ Add New Node",
        'nodes_list': "📋 Available Nodes:",
        'no_nodes': "⚠️ No nodes found for this panel. Would you like to add a new node?",
        'node_info': "ℹ️ Node Information",
        'reconnect_node': "🔄 Reconnect Node",
        'delete_node': "🗑️ Delete Node",
        'update_node': "🔄 Update Information",
        'back': "⬅️ Back",

        # Node installation
        'install_type': "Please select the installation method:",
        'single_install': "🖥️ Single Server Installation",
        'bulk_install': "📦 Bulk Installation (Multiple Servers)",
        'enter_ssh_ip': "Please enter the server IP address:",
        'enter_ssh_port': "Please enter the SSH port (default is 22):",
        'enter_ssh_username': "Please enter the SSH username:",
        'auth_method': "Please select the authentication method:",
        'password_auth': "🔒 Password Authentication",
        'ssh_key_auth': "🔑 SSH Key Authentication",
        'enter_ssh_password': "Please enter the SSH password:",
        'enter_ssh_key': "🔑 Please send your SSH private key:\n\n💡 Important: Send the PRIVATE key, not the public key.\n📝 You can upload the file or paste the key content.",
        'port_config': "Please configure the ports for your node:",
        'custom_ports': "⚙️ Custom Port Configuration",
        'random_ports': "🎲 Random Port Assignment",
        'enter_node_port': "Please enter the node port number:",
        'enter_api_port': "Please enter the API port number:",
        'enter_node_name': "Please enter a name for this node:",
        'random_name': "🎲 Generate Random Name",
        'installing_node': "🚀 Installing node on server... This process may take several minutes. Please wait.",
        'node_installed': "✅ Node has been successfully installed and is now operational.",
        'installation_failed': "❌ Installation failed with error: {error}\n\nPlease check your server configuration and try again.",

        # Admin features
        'admin_only': "🚫 Access denied. This function is restricted to administrators only.",
        'not_sudo': "🔒 Insufficient privileges. This operation requires sudo access.",
        'backup_created': "✅ Backup has been successfully created and saved.",
        'stats_title': "📊 System Statistics",
        'total_panels': "Total Panels: {count}",
        'total_nodes': "Total Nodes: {count}",
        'active_sessions': "Active Sessions: {count}",
        'add_admin': "👤 Add Administrator",
        'import_backup': "📥 Import Backup",
        'select_admin_permissions': "🔐 Please select the permissions for the new administrator:",
        'can_manage_panels': "🎛️ Panel Management",
        'can_manage_nodes': "🖥️ Node Management",
        'can_view_stats': "📊 View Statistics",
        'can_backup': "💾 Backup Management",
        'can_add_admins': "👥 Administrator Management",
        'confirm': "✅ Confirm",
        'cancel': "❌ Cancel",
        'enter_admin_user_id': "Please enter the Telegram user ID of the new administrator:",
        'user_already_admin': "⚠️ This user is already an administrator.",
        'admin_added_successfully': "✅ Administrator successfully added!\nUser ID: {user_id}",
        'error_adding_admin': "❌ Failed to add administrator. Please try again.",
        'invalid_user_id': "❌ Invalid user ID. Please enter a valid numeric ID.",
        'send_backup_file': "📤 Please send the backup file (.db format):",
        'choose_import_method': "🔄 Please select the import method:",
        'merge_databases': "🔗 Merge with Current Database",
        'replace_database': "🔄 Replace Current Database",
        'invalid_backup_file': "❌ Invalid file format. Please send a .db file.",
        'error_processing_backup': "❌ Error processing backup: {error}",
        'backup_merged_successfully': "✅ Backup has been successfully merged with the current database.",
        'error_merging_backup': "❌ Error merging backup: {error}",
        'panel_conflict_detected': "⚠️ Conflict detected!\n\n📋 Backup Panel: {backup_name}\n📋 Current Panel: {current_name}\n🌐 URL: {url}\n\nWhat would you like to do?",
        'replace_with_backup': "🔄 Replace with Backup",
        'keep_current': "⏭️ Skip",
        'database_replaced_successfully': "✅ Database successfully replaced!\n💾 Previous version backed up as: {backup_file}",
        'error_replacing_database': "❌ Error replacing database: {error}",

        # Errors
        'error_occurred': "❌ An error has occurred: {error}",
        'invalid_url': "❌ Invalid URL format. Please check and try again.",
        'connection_timeout': "⏰ Connection timeout. Please check your network and try again.",
        'authentication_failed': "🔑 Authentication failed. Please verify your credentials.",
        'node_not_found': "🔍 Node not found. Please check the node ID and try again.",
        'operation_cancelled': "✋ Operation has been cancelled by user.",
        'session_expired': "⏰ Your session has expired. Please start over.",

        # Success messages
        'operation_successful': "✅ Operation completed successfully.",
        'node_reconnected': "🔄 Node has been successfully reconnected.",
        'node_deleted': "🗑️ Node has been successfully deleted.",
        'node_updated': "🔄 Node information has been updated.",

        # SSH validation
        'invalid_ssh_key_format': "❌ Invalid SSH key format. The key should start with -----BEGIN",
        'testing_ssh_connection': "🔄 Testing SSH connection...",
        'ssh_test_success': "✅ SSH connection test successful.",
        'ssh_test_failed': "❌ SSH connection test failed: {error}",

        # Bulk installation
        'bulk_auth_choice': "🔐 Please select the authentication method for bulk installation:",
        'bulk_password_auth': "🔒 Password-based Authentication",
        'bulk_ssh_key_auth': "🔑 SSH Key Authentication",
        'bulk_enter_servers_with_password': "📋 Please enter the server list in the following format (one per line):\nIP USERNAME PASSWORD\nIP USERNAME PASSWORD\n\nExample:\n192.168.1.1 root mypassword123\n192.168.1.2 admin myotherpass",
        'bulk_enter_servers_for_ssh': "📋 Please enter the server list in the following format (one per line):\nIP USERNAME\nIP USERNAME\n\nExample:\n192.168.1.1 root\n192.168.1.2 admin",
        'bulk_enter_ssh_key': "🔑 Please send the SSH private key that will be used for all servers:",
        'enter_server_list': "📋 Please enter the server list in the following format (one per line):\nIP USERNAME PASSWORD_OR_SSH_KEY\n\nExamples:\n192.168.1.1 root mypassword\n192.168.1.2 admin -----BEGIN OPENSSH PRIVATE KEY-----\nMIIEpAIB...\n-----END OPENSSH PRIVATE KEY-----",
        'bulk_auth_method': "🔐 Please select the authentication method for servers:",
        'enter_bulk_password': "🔒 Please enter the common password for all servers:",
        'enter_bulk_ssh_key': "🔑 Please send the SSH private key for all servers:",
        'invalid_server_format': "❌ Invalid server format. Please enter servers in the correct format.",
        'installing_bulk_nodes': "🚀 Installing nodes on multiple servers... This process may take a considerable amount of time.",
        'bulk_install_complete': "📊 Bulk installation completed!\n✅ Successful: {successful}\n❌ Failed: {failed}",
        'network_error': "🌐 Network connection error. Please check your internet connection.",
        'server_error': "🔧 Server error occurred. Please try again later.",
        'permission_denied': "🚫 Permission denied. Please check your access rights.",
        'file_not_found': "📁 File not found. Please verify the file path.",
        'invalid_input': "❌ Invalid input provided. Please check your data and try again.",
    },

    'fa': {
        # Start and language selection
        'welcome': "🎉 به ربات مدیریت نودهای مرزبان خوش آمدید! 🚀\n\nاین ربات به شما کمک می‌کند تا به راحتی نودهای مرزبان را نصب و مدیریت کنید.",
        'select_language': "🌍 لطفاً زبان مورد نظر خود را برای ارتباط انتخاب کنید:",
        'language_selected': "✅ زبان با موفقیت به فارسی تنظیم شد.",

        # Main menu
        'main_menu': "🏠 منوی اصلی",
        'main_menu_desc': "لطفاً عملیات مورد نظر خود را انتخاب کنید:",
        'add_panel': "➕ افزودن پنل جدید",
        'manage_nodes': "🔧 مدیریت نودها",
        'admin_panel': "👑 پنل مدیریت",
        'backup_data': "💾 مدیریت پشتیبان‌گیری",
        'statistics': "📊 مشاهده آمار",

        # Panel management
        'panel_type': "لطفاً نوع پنلی که می‌خواهید اضافه کنید را انتخاب کنید:",
        'marzban_panel': "🚀 پنل مرزبان",
        'enter_panel_url': "لطفاً آدرس پنل خود را وارد کنید (بدون /dashboard یا مسیرهای اضافی):\n\nنمونه: https://your-domain.com",
        'enter_username': "لطفاً نام کاربری ادمین را وارد کنید (اطمینان حاصل کنید که دسترسی sudo دارد):",
        'enter_password': "لطفاً رمز عبور ادمین را وارد کنید:",
        'enter_panel_name': "لطفاً نامی برای این پنل جهت شناسایی آسان وارد کنید:",
        'panel_saved': "✅ پنل با موفقیت ذخیره شد و آماده استفاده است.",
        'panel_connection_failed': "❌ اتصال به پنل ناموفق بود. لطفاً اطلاعات ورودی خود را بررسی کرده و دوباره تلاش کنید.",

        # Node management
        'select_panel': "لطفاً پنلی که می‌خواهید با آن کار کنید را انتخاب کنید:",
        'no_panels': "⚠️ هنوز پنلی اضافه نشده است. لطفاً ابتدا یک پنل اضافه کنید.",
        'node_management': "🔧 مرکز مدیریت نودها",
        'list_nodes': "📋 فهرست همه نودها",
        'get_node_info': "ℹ️ مشاهده جزئیات نود",
        'add_new_node': "➕ افزودن نود جدید",
        'nodes_list': "📋 نودهای موجود:",
        'no_nodes': "⚠️ هیچ نودی برای این پنل یافت نشد. آیا می‌خواهید نود جدیدی اضافه کنید؟",
        'node_info': "ℹ️ اطلاعات نود",
        'reconnect_node': "🔄 اتصال مجدد نود",
        'delete_node': "🗑️ حذف نود",
        'update_node': "🔄 بروزرسانی اطلاعات",
        'back': "⬅️ بازگشت",

        # Node installation
        'install_type': "لطفاً روش نصب را انتخاب کنید:",
        'single_install': "🖥️ نصب تک سرور",
        'bulk_install': "📦 نصب گروهی (چندین سرور)",
        'enter_ssh_ip': "لطفاً آدرس IP سرور را وارد کنید:",
        'enter_ssh_port': "لطفاً پورت SSH را وارد کنید (پیش‌فرض 22):",
        'enter_ssh_username': "لطفاً نام کاربری SSH را وارد کنید:",
        'auth_method': "لطفاً روش احراز هویت را انتخاب کنید:",
        'password_auth': "🔒 احراز هویت با رمز عبور",
        'ssh_key_auth': "🔑 احراز هویت با کلید SSH",
        'enter_ssh_password': "لطفاً رمز عبور SSH را وارد کنید:",
        'enter_ssh_key': "🔑 لطفاً کلید خصوصی SSH خود را ارسال کنید:\n\n💡 مهم: کلید خصوصی (PRIVATE) را ارسال کنید، نه کلید عمومی.\n📝 می‌توانید فایل را آپلود کنید یا محتوای کلید را کپی کنید.",
        'port_config': "لطفاً پورت‌های نود خود را پیکربندی کنید:",
        'custom_ports': "⚙️ پیکربندی پورت دلخواه",
        'random_ports': "🎲 تخصیص پورت تصادفی",
        'enter_node_port': "لطفاً شماره پورت نود را وارد کنید:",
        'enter_api_port': "لطفاً شماره پورت API را وارد کنید:",
        'enter_node_name': "لطفاً نامی برای این نود وارد کنید:",
        'random_name': "🎲 تولید نام تصادفی",
        'installing_node': "🚀 در حال نصب نود بر روی سرور... این فرآیند ممکن است چندین دقیقه طول بکشد. لطفاً صبر کنید.",
        'node_installed': "✅ نود با موفقیت نصب شد و اکنون عملیاتی است.",
        'installation_failed': "❌ نصب با خطای زیر ناموفق بود: {error}\n\nلطفاً تنظیمات سرور خود را بررسی کرده و دوباره تلاش کنید.",

        # Admin features
        'admin_only': "🚫 دسترسی مجاز نیست. این عملکرد محدود به مدیران سیستم است.",
        'not_sudo': "🔒 دسترسی ناکافی. این عملیات نیاز به دسترسی sudo دارد.",
        'backup_created': "✅ پشتیبان‌گیری با موفقیت انجام شد و ذخیره گردید.",
        'stats_title': "📊 آمار سیستم",
        'total_panels': "کل پنل‌ها: {count}",
        'total_nodes': "کل نودها: {count}",
        'active_sessions': "جلسات فعال: {count}",
        'add_admin': "👤 افزودن مدیر",
        'import_backup': "📥 وارد کردن پشتیبان",
        'select_admin_permissions': "🔐 لطفاً مجوزهای مدیر جدید را انتخاب کنید:",
        'can_manage_panels': "🎛️ مدیریت پنل‌ها",
        'can_manage_nodes': "🖥️ مدیریت نودها",
        'can_view_stats': "📊 مشاهده آمار",
        'can_backup': "💾 مدیریت پشتیبان‌گیری",
        'can_add_admins': "👥 مدیریت مدیران",
        'confirm': "✅ تأیید",
        'cancel': "❌ انصراف",
        'enter_admin_user_id': "لطفاً شناسه کاربری تلگرام مدیر جدید را وارد کنید:",
        'user_already_admin': "⚠️ این کاربر هم‌اکنون مدیر سیستم است.",
        'admin_added_successfully': "✅ مدیر با موفقیت اضافه شد!\nشناسه کاربری: {user_id}",
        'error_adding_admin': "❌ افزودن مدیر ناموفق بود. لطفاً دوباره تلاش کنید.",
        'invalid_user_id': "❌ شناسه کاربری نامعتبر. لطفاً یک شناسه عددی معتبر وارد کنید.",
        'send_backup_file': "📤 لطفاً فایل پشتیبان (فرمت .db) را ارسال کنید:",
        'choose_import_method': "🔄 لطفاً روش وارد کردن را انتخاب کنید:",
        'merge_databases': "🔗 ادغام با پایگاه داده فعلی",
        'replace_database': "🔄 جایگزینی پایگاه داده فعلی",
        'invalid_backup_file': "❌ فرمت فایل نامعتبر. لطفاً فایل .db ارسال کنید.",
        'error_processing_backup': "❌ خطا در پردازش پشتیبان: {error}",
        'backup_merged_successfully': "✅ پشتیبان با موفقیت با پایگاه داده فعلی ادغام شد.",
        'error_merging_backup': "❌ خطا در ادغام پشتیبان: {error}",
        'panel_conflict_detected': "⚠️ تضاد شناسایی شد!\n\n📋 پنل پشتیبان: {backup_name}\n📋 پنل فعلی: {current_name}\n🌐 آدرس: {url}\n\nچه کاری انجام دهیم؟",
        'replace_with_backup': "🔄 جایگزینی با پشتیبان",
        'keep_current': "⏭️ رد کردن",
        'database_replaced_successfully': "✅ پایگاه داده با موفقیت جایگزین شد!\n💾 نسخه قبلی پشتیبان‌گیری شد: {backup_file}",
        'error_replacing_database': "❌ خطا در جایگزینی پایگاه داده: {error}",

        # Errors
        'error_occurred': "❌ خطایی رخ داده است: {error}",
        'invalid_url': "❌ فرمت آدرس نامعتبر. لطفاً بررسی کرده و دوباره تلاش کنید.",
        'connection_timeout': "⏰ زمان اتصال به پایان رسید. لطفاً اتصال شبکه خود را بررسی کرده و دوباره تلاش کنید.",
        'authentication_failed': "🔑 احراز هویت ناموفق بود. لطفاً اطلاعات ورودی خود را تأیید کنید.",
        'node_not_found': "🔍 نود یافت نشد. لطفاً شناسه نود را بررسی کرده و دوباره تلاش کنید.",
        'operation_cancelled': "✋ عملیات توسط کاربر لغو شد.",
        'session_expired': "⏰ جلسه شما منقضی شده است. لطفاً دوباره شروع کنید.",

        # Success messages
        'operation_successful': "✅ عملیات با موفقیت انجام شد.",
        'node_reconnected': "🔄 نود با موفقیت مجدداً متصل شد.",
        'node_deleted': "🗑️ نود با موفقیت حذف شد.",
        'node_updated': "🔄 اطلاعات نود بروزرسانی شد.",

        # SSH validation
        'invalid_ssh_key_format': "❌ فرمت کلید SSH نامعتبر. کلید باید با -----BEGIN شروع شود.",
        'testing_ssh_connection': "🔄 در حال تست اتصال SSH...",
        'ssh_test_success': "✅ تست اتصال SSH موفقیت‌آمیز بود.",
        'ssh_test_failed': "❌ تست اتصال SSH ناموفق بود: {error}",

        # Bulk installation
        'bulk_auth_choice': "🔐 لطفاً روش احراز هویت برای نصب گروهی را انتخاب کنید:",
        'bulk_password_auth': "🔒 احراز هویت مبتنی بر رمز عبور",
        'bulk_ssh_key_auth': "🔑 احراز هویت با کلید SSH",
        'bulk_enter_servers_with_password': "📋 لطفاً فهرست سرورها را با فرمت زیر وارد کنید (هر کدام در یک خط):\nIP USERNAME PASSWORD\nIP USERNAME PASSWORD\n\nنمونه:\n192.168.1.1 root mypassword123\n192.168.1.2 admin myotherpass",
        'bulk_enter_servers_for_ssh': "📋 لطفاً فهرست سرورها را با فرمت زیر وارد کنید (هر کدام در یک خط):\nIP USERNAME\nIP USERNAME\n\nنمونه:\n192.168.1.1 root\n192.168.1.2 admin",
        'bulk_enter_ssh_key': "🔑 لطفاً کلید خصوصی SSH که برای همه سرورها استفاده خواهد شد را ارسال کنید:",
        'enter_server_list': "📋 لطفاً فهرست سرورها را با فرمت زیر وارد کنید (هر کدام در یک خط):\nIP USERNAME PASSWORD_OR_SSH_KEY\n\nنمونه‌ها:\n192.168.1.1 root mypassword\n192.168.1.2 admin -----BEGIN OPENSSH PRIVATE KEY-----\nMIIEpAIB...\n-----END OPENSSH PRIVATE KEY-----",
        'bulk_auth_method': "🔐 لطفاً روش احراز هویت برای سرورها را انتخاب کنید:",
        'enter_bulk_password': "🔒 لطفاً رمز عبور مشترک برای همه سرورها را وارد کنید:",
        'enter_bulk_ssh_key': "🔑 لطفاً کلید خصوصی SSH برای همه سرورها را ارسال کنید:",
        'invalid_server_format': "❌ فرمت سرور نامعتبر. لطفاً سرورها را با فرمت صحیح وارد کنید.",
        'installing_bulk_nodes': "🚀 در حال نصب نودها بر روی چندین سرور... این فرآیند ممکن است زمان قابل توجهی طول بکشد.",
        'bulk_install_complete': "📊 نصب گروهی تکمیل شد!\n✅ موفق: {successful}\n❌ ناموفق: {failed}",
        'network_error': "🌐 خطای اتصال شبکه. لطفاً اتصال اینترنت خود را بررسی کنید.",
        'server_error': "🔧 خطای سرور رخ داده است. لطفاً بعداً دوباره تلاش کنید.",
        'permission_denied': "🚫 دسترسی مجاز نیست. لطفاً حقوق دسترسی خود را بررسی کنید.",
        'file_not_found': "📁 فایل یافت نشد. لطفاً مسیر فایل را تأیید کنید.",
        'invalid_input': "❌ ورودی نامعتبر ارائه شده. لطفاً داده‌های خود را بررسی کرده و دوباره تلاش کنید.",
    },

    'ru': {
        # Start and language selection
        'welcome': "🎉 Добро пожаловать в бот управления узлами Marzban! 🚀\n\nЭтот бот поможет вам легко устанавливать и управлять узлами Marzban через удобный интерфейс.",
        'select_language': "🌍 Пожалуйста, выберите предпочтительный язык для общения:",
        'language_selected': "✅ Язык успешно установлен на русский.",

        # Main menu
        'main_menu': "🏠 Главное меню",
        'main_menu_desc': "Пожалуйста, выберите операцию, которую хотите выполнить:",
        'add_panel': "➕ Добавить новую панель",
        'manage_nodes': "🔧 Управление узлами",
        'admin_panel': "👑 Панель администратора",
        'backup_data': "💾 Управление резервными копиями",
        'statistics': "📊 Просмотр статистики",

        # Panel management
        'panel_type': "Пожалуйста, выберите тип панели, которую хотите добавить:",
        'marzban_panel': "🚀 Панель Marzban",
        'enter_panel_url': "Пожалуйста, введите URL вашей панели (без /dashboard или других путей):\n\nПример: https://your-domain.com",
        'enter_username': "Пожалуйста, введите имя пользователя администратора (убедитесь, что у него есть права sudo):",
        'enter_password': "Пожалуйста, введите пароль администратора:",
        'enter_panel_name': "Пожалуйста, введите имя для этой панели для удобной идентификации:",
        'panel_saved': "✅ Панель успешно сохранена и готова к использованию.",
        'panel_connection_failed': "❌ Не удалось подключиться к панели. Пожалуйста, проверьте ваши учетные данные и попробуйте снова.",

        # Node management
        'select_panel': "Пожалуйста, выберите панель, с которой хотите работать:",
        'no_panels': "⚠️ Панели еще не добавлены. Пожалуйста, сначала добавьте панель.",
        'node_management': "🔧 Центр управления узлами",
        'list_nodes': "📋 Список всех узлов",
        'get_node_info': "ℹ️ Просмотр деталей узла",
        'add_new_node': "➕ Добавить новый узел",
        'nodes_list': "📋 Доступные узлы:",
        'no_nodes': "⚠️ Узлы для этой панели не найдены. Хотите добавить новый узел?",
        'node_info': "ℹ️ Информация об узле",
        'reconnect_node': "🔄 Переподключить узел",
        'delete_node': "🗑️ Удалить узел",
        'update_node': "🔄 Обновить информацию",
        'back': "⬅️ Назад",

        # Node installation
        'install_type': "Пожалуйста, выберите метод установки:",
        'single_install': "🖥️ Установка на один сервер",
        'bulk_install': "📦 Массовая установка (несколько серверов)",
        'enter_ssh_ip': "Пожалуйста, введите IP-адрес сервера:",
        'enter_ssh_port': "Пожалуйста, введите SSH порт (по умолчанию 22):",
        'enter_ssh_username': "Пожалуйста, введите имя пользователя SSH:",
        'auth_method': "Пожалуйста, выберите метод аутентификации:",
        'password_auth': "🔒 Аутентификация по паролю",
        'ssh_key_auth': "🔑 Аутентификация по SSH ключу",
        'enter_ssh_password': "Пожалуйста, введите SSH пароль:",
        'enter_ssh_key': "🔑 Пожалуйста, отправьте ваш приватный SSH ключ:\n\n💡 Важно: Отправьте приватный ключ, а не публичный.\n📝 Вы можете загрузить файл или вставить содержимое ключа.",
        'port_config': "Пожалуйста, настройте порты для вашего узла:",
        'custom_ports': "⚙️ Пользовательская настройка портов",
        'random_ports': "🎲 Случайное назначение портов",
        'enter_node_port': "Пожалуйста, введите номер порта узла:",
        'enter_api_port': "Пожалуйста, введите номер API порта:",
        'enter_node_name': "Пожалуйста, введите имя для этого узла:",
        'random_name': "🎲 Сгенерировать случайное имя",
        'installing_node': "🚀 Установка узла на сервер... Этот процесс может занять несколько минут. Пожалуйста, подождите.",
        'node_installed': "✅ Узел успешно установлен и теперь работает.",
        'installation_failed': "❌ Установка завершилась с ошибкой: {error}\n\nПожалуйста, проверьте конфигурацию сервера и попробуйте снова.",

        # Admin features
        'admin_only': "🚫 Доступ запрещен. Эта функция ограничена только для администраторов.",
        'not_sudo': "🔒 Недостаточно прав. Эта операция требует sudo доступа.",
        'backup_created': "✅ Резервная копия успешно создана и сохранена.",
        'stats_title': "📊 Статистика системы",
        'total_panels': "Всего панелей: {count}",
        'total_nodes': "Всего узлов: {count}",
        'active_sessions': "Активных сессий: {count}",
        'add_admin': "👤 Добавить администратора",
        'import_backup': "📥 Импортировать резервную копию",
        'select_admin_permissions': "🔐 Пожалуйста, выберите разрешения для нового администратора:",
        'can_manage_panels': "🎛️ Управление панелями",
        'can_manage_nodes': "🖥️ Управление узлами",
        'can_view_stats': "📊 Просмотр статистики",
        'can_backup': "💾 Управление резервными копиями",
        'can_add_admins': "👥 Управление администраторами",
        'confirm': "✅ Подтвердить",
        'cancel': "❌ Отмена",
        'enter_admin_user_id': "Пожалуйста, введите Telegram ID нового администратора:",
        'user_already_admin': "⚠️ Этот пользователь уже является администратором.",
        'admin_added_successfully': "✅ Администратор успешно добавлен!\nID пользователя: {user_id}",
        'error_adding_admin': "❌ Не удалось добавить администратора. Пожалуйста, попробуйте снова.",
        'invalid_user_id': "❌ Неверный ID пользователя. Пожалуйста, введите действительный числовой ID.",
        'send_backup_file': "📤 Пожалуйста, отправьте файл резервной копии (формат .db):",
        'choose_import_method': "🔄 Пожалуйста, выберите метод импорта:",
        'merge_databases': "🔗 Объединить с текущей базой данных",
        'replace_database': "🔄 Заменить текущую базу данных",
        'invalid_backup_file': "❌ Неверный формат файла. Пожалуйста, отправьте файл .db.",
        'error_processing_backup': "❌ Ошибка обработки резервной копии: {error}",
        'backup_merged_successfully': "✅ Резервная копия успешно объединена с текущей базой данных.",
        'error_merging_backup': "❌ Ошибка объединения резервной копии: {error}",
        'panel_conflict_detected': "⚠️ Обнаружен конфликт!\n\n📋 Панель из резервной копии: {backup_name}\n📋 Текущая панель: {current_name}\n🌐 URL: {url}\n\nЧто вы хотите сделать?",
        'replace_with_backup': "🔄 Заменить резервной копией",
        'keep_current': "⏭️ Пропустить",
        'database_replaced_successfully': "✅ База данных успешно заменена!\n💾 Предыдущая версия сохранена как: {backup_file}",
        'error_replacing_database': "❌ Ошибка замены базы данных: {error}",

        # Errors
        'error_occurred': "❌ Произошла ошибка: {error}",
        'invalid_url': "❌ Неверный формат URL. Пожалуйста, проверьте и попробуйте снова.",
        'connection_timeout': "⏰ Время ожидания соединения истекло. Пожалуйста, проверьте ваше сетевое соединение и попробуйте снова.",
        'authentication_failed': "🔑 Аутентификация не удалась. Пожалуйста, проверьте ваши учетные данные.",
        'node_not_found': "🔍 Узел не найден. Пожалуйста, проверьте ID узла и попробуйте снова.",
        'operation_cancelled': "✋ Операция была отменена пользователем.",
        'session_expired': "⏰ Ваша сессия истекла. Пожалуйста, начните заново.",

        # Success messages
        'operation_successful': "✅ Операция выполнена успешно.",
        'node_reconnected': "🔄 Узел успешно переподключен.",
        'node_deleted': "🗑️ Узел успешно удален.",
        'node_updated': "🔄 Информация об узле обновлена.",

        # SSH validation
        'invalid_ssh_key_format': "❌ Неверный формат SSH ключа. Ключ должен начинаться с -----BEGIN",
        'testing_ssh_connection': "🔄 Тестирование SSH соединения...",
        'ssh_test_success': "✅ Тест SSH соединения прошел успешно.",
        'ssh_test_failed': "❌ Тест SSH соединения не удался: {error}",

        # Bulk installation
        'bulk_auth_choice': "🔐 Пожалуйста, выберите метод аутентификации для массовой установки:",
        'bulk_password_auth': "🔒 Аутентификация на основе пароля",
        'bulk_ssh_key_auth': "🔑 Аутентификация SSH ключом",
        'bulk_enter_servers_with_password': "📋 Пожалуйста, введите список серверов в следующем формате (по одному в строке):\nIP USERNAME PASSWORD\nIP USERNAME PASSWORD\n\nПример:\n192.168.1.1 root mypassword123\n192.168.1.2 admin myotherpass",
        'bulk_enter_servers_for_ssh': "📋 Пожалуйста, введите список серверов в следующем формате (по одному в строке):\nIP USERNAME\nIP USERNAME\n\nПример:\n192.168.1.1 root\n192.168.1.2 admin",
        'bulk_enter_ssh_key': "🔑 Пожалуйста, отправьте приватный SSH ключ, который будет использоваться для всех серверов:",
        'enter_server_list': "📋 Пожалуйста, введите список серверов в следующем формате (по одному в строке):\nIP USERNAME PASSWORD_OR_SSH_KEY\n\nПримеры:\n192.168.1.1 root mypassword\n192.168.1.2 admin -----BEGIN OPENSSH PRIVATE KEY-----\nMIIEpAIB...\n-----END OPENSSH PRIVATE KEY-----",
        'bulk_auth_method': "🔐 Пожалуйста, выберите метод аутентификации для серверов:",
        'enter_bulk_password': "🔒 Пожалуйста, введите общий пароль для всех серверов:",
        'enter_bulk_ssh_key': "🔑 Пожалуйста, отправьте приватный SSH ключ для всех серверов:",
        'invalid_server_format': "❌ Неверный формат сервера. Пожалуйста, введите серверы в правильном формате.",
        'installing_bulk_nodes': "🚀 Установка узлов на несколько серверов... Этот процесс может занять значительное время.",
        'bulk_install_complete': "📊 Массовая установка завершена!\n✅ Успешно: {successful}\n❌ Не удалось: {failed}",
        'network_error': "🌐 Ошибка сетевого соединения. Пожалуйста, проверьте ваше интернет-соединение.",
        'server_error': "🔧 Произошла ошибка сервера. Пожалуйста, попробуйте позже.",
        'permission_denied': "🚫 Доступ запрещен. Пожалуйста, проверьте ваши права доступа.",
        'file_not_found': "📁 Файл не найден. Пожалуйста, проверьте путь к файлу.",
        'invalid_input': "❌ Предоставлен неверный ввод. Пожалуйста, проверьте ваши данные и попробуйте снова.",
        'session_expired': "⏰ Ваша сессия истекла. Пожалуйста, начните заново.",
    },

    'ar': {
        # Start and language selection
        'welcome': "🎉 مرحباً بكم في بوت إدارة عقد Marzban! 🚀\n\nيساعدك هذا البوت على تثبيت وإدارة عقد Marzban بسهولة من خلال واجهة سهلة الاستخدام.",
        'select_language': "🌍 يرجى اختيار لغتك المفضلة للتواصل:",
        'language_selected': "✅ تم تعيين اللغة بنجاح إلى العربية.",

        # Main menu
        'main_menu': "🏠 القائمة الرئيسية",
        'main_menu_desc': "يرجى اختيار العملية التي تريد تنفيذها:",
        'add_panel': "➕ إضافة لوحة جديدة",
        'manage_nodes': "🔧 إدارة العقد",
        'admin_panel': "👑 لوحة الإدارة",
        'backup_data': "💾 إدارة النسخ الاحتياطية",
        'statistics': "📊 عرض الإحصائيات",

        # Panel management
        'panel_type': "يرجى اختيار نوع اللوحة التي تريد إضافتها:",
        'marzban_panel': "🚀 لوحة Marzban",
        'enter_panel_url': "يرجى إدخال رابط لوحتك (بدون /dashboard أو مسارات أخرى):\n\nمثال: https://your-domain.com",
        'enter_username': "يرجى إدخال اسم المستخدم الإداري (تأكد من وجود صلاحيات sudo):",
        'enter_password': "يرجى إدخال كلمة مرور الإدارة:",
        'enter_panel_name': "يرجى إدخال اسم لهذه اللوحة لسهولة التعرف عليها:",
        'panel_saved': "✅ تم حفظ اللوحة بنجاح وهي جاهزة للاستخدام.",
        'panel_connection_failed': "❌ فشل في الاتصال باللوحة. يرجى التحقق من بيانات الاعتماد والمحاولة مرة أخرى.",

        # Node management
        'select_panel': "يرجى اختيار اللوحة التي تريد العمل معها:",
        'no_panels': "⚠️ لم تتم إضافة أي لوحات بعد. يرجى إضافة لوحة أولاً.",
        'node_management': "🔧 مركز إدارة العقد",
        'list_nodes': "📋 قائمة جميع العقد",
        'get_node_info': "ℹ️ عرض تفاصيل العقدة",
        'add_new_node': "➕ إضافة عقدة جديدة",
        'nodes_list': "📋 العقد المتاحة:",
        'no_nodes': "⚠️ لم يتم العثور على عقد لهذه اللوحة. هل تريد إضافة عقدة جديدة؟",
        'node_info': "ℹ️ معلومات العقدة",
        'reconnect_node': "🔄 إعادة توصيل العقدة",
        'delete_node': "🗑️ حذف العقدة",
        'update_node': "🔄 تحديث المعلومات",
        'back': "⬅️ رجوع",

        # Node installation
        'install_type': "يرجى اختيار طريقة التثبيت:",
        'single_install': "🖥️ تثبيت خادم واحد",
        'bulk_install': "📦 التثبيت الجماعي (عدة خوادم)",
        'enter_ssh_ip': "يرجى إدخال عنوان IP للخادم:",
        'enter_ssh_port': "يرجى إدخال منفذ SSH (الافتراضي 22):",
        'enter_ssh_username': "يرجى إدخال اسم مستخدم SSH:",
        'auth_method': "يرجى اختيار طريقة المصادقة:",
        'password_auth': "🔒 المصادقة بكلمة المرور",
        'ssh_key_auth': "🔑 المصادقة بمفتاح SSH",
        'enter_ssh_password': "يرجى إدخال كلمة مرور SSH:",
        'enter_ssh_key': "🔑 يرجى إرسال مفتاح SSH الخاص بك:\n\n💡 مهم: أرسل المفتاح الخاص، وليس العام.\n📝 يمكنك رفع الملف أو نسخ محتوى المفتاح.",
        'port_config': "يرجى تكوين المنافذ لعقدتك:",
        'custom_ports': "⚙️ تكوين منافذ مخصصة",
        'random_ports': "🎲 تعيين منافذ عشوائية",
        'enter_node_port': "يرجى إدخال رقم منفذ العقدة:",
        'enter_api_port': "يرجى إدخال رقم منفذ API:",
        'enter_node_name': "يرجى إدخال اسم لهذه العقدة:",
        'random_name': "🎲 إنشاء اسم عشوائي",
        'installing_node': "🚀 تثبيت العقدة على الخادم... قد تستغرق هذه العملية عدة دقائق. يرجى الانتظار.",
        'node_installed': "✅ تم تثبيت العقدة بنجاح وهي الآن قيد التشغيل.",
        'installation_failed': "❌ فشل التثبيت مع الخطأ: {error}\n\nيرجى التحقق من تكوين الخادم والمحاولة مرة أخرى.",

        # Admin features
        'admin_only': "🚫 تم رفض الوصول. هذه الوظيفة مقتصرة على المديرين فقط.",
        'not_sudo': "🔒 امتيازات غير كافية. تتطلب هذه العملية وصول sudo.",
        'backup_created': "✅ تم إنشاء النسخة الاحتياطية وحفظها بنجاح.",
        'stats_title': "📊 إحصائيات النظام",
        'total_panels': "إجمالي اللوحات: {count}",
        'total_nodes': "إجمالي العقد: {count}",
        'active_sessions': "الجلسات النشطة: {count}",
        'add_admin': "👤 إضافة مدير",
        'import_backup': "📥 استيراد نسخة احتياطية",
        'select_admin_permissions': "🔐 يرجى اختيار الأذونات للمدير الجديد:",
        'can_manage_panels': "🎛️ إدارة اللوحات",
        'can_manage_nodes': "🖥️ إدارة العقد",
        'can_view_stats': "📊 عرض الإحصائيات",
        'can_backup': "💾 إدارة النسخ الاحتياطية",
        'can_add_admins': "👥 إدارة المديرين",
        'confirm': "✅ تأكيد",
        'cancel': "❌ إلغاء",
        'enter_admin_user_id': "يرجى إدخال معرف Telegram للمدير الجديد:",
        'user_already_admin': "⚠️ هذا المستخدم مدير بالفعل.",
        'admin_added_successfully': "✅ تم إضافة المدير بنجاح!\nمعرف المستخدم: {user_id}",
        'error_adding_admin': "❌ فشل في إضافة المدير. يرجى المحاولة مرة أخرى.",
        'invalid_user_id': "❌ معرف مستخدم غير صحيح. يرجى إدخال معرف رقمي صحيح.",
        'send_backup_file': "📤 يرجى إرسال ملف النسخة الاحتياطية (تنسيق .db):",
        'choose_import_method': "🔄 يرجى اختيار طريقة الاستيراد:",
        'merge_databases': "🔗 دمج مع قاعدة البيانات الحالية",
        'replace_database': "🔄 استبدال قاعدة البيانات الحالية",
        'invalid_backup_file': "❌ تنسيق ملف غير صحيح. يرجى إرسال ملف .db.",
        'error_processing_backup': "❌ خطأ في معالجة النسخة الاحتياطية: {error}",
        'backup_merged_successfully': "✅ تم دمج النسخة الاحتياطية بنجاح مع قاعدة البيانات الحالية.",
        'error_merging_backup': "❌ خطأ في دمج النسخة الاحتياطية: {error}",
        'panel_conflict_detected': "⚠️ تم اكتشاف تعارض!\n\n📋 لوحة النسخة الاحتياطية: {backup_name}\n📋 اللوحة الحالية: {current_name}\n🌐 الرابط: {url}\n\nماذا تريد أن تفعل؟",
        'replace_with_backup': "🔄 استبدال بالنسخة الاحتياطية",
        'keep_current': "⏭️ تخطي",
        'database_replaced_successfully': "✅ تم استبدال قاعدة البيانات بنجاح!\n💾 تم حفظ النسخة السابقة كـ: {backup_file}",
        'error_replacing_database': "❌ خطأ في استبدال قاعدة البيانات: {error}",

        # Errors
        'error_occurred': "❌ حدث خطأ: {error}",
        'invalid_url': "❌ تنسيق رابط غير صحيح. يرجى التحقق والمحاولة مرة أخرى.",
        'connection_timeout': "⏰ انتهت مهلة الاتصال. يرجى التحقق من اتصالك بالشبكة والمحاولة مرة أخرى.",
        'authentication_failed': "🔑 فشلت المصادقة. يرجى التحقق من بيانات الاعتماد الخاصة بك.",
        'node_not_found': "🔍 العقدة غير موجودة. يرجى التحقق من معرف العقدة والمحاولة مرة أخرى.",
        'operation_cancelled': "✋ تم إلغاء العملية من قبل المستخدم.",
        'session_expired': "⏰ انتهت صلاحية جلستك. يرجى البدء من جديد.",

        # Success messages
        'operation_successful': "✅ تم إنجاز العملية بنجاح.",
        'node_reconnected': "🔄 تم إعادة توصيل العقدة بنجاح.",
        'node_deleted': "🗑️ تم حذف العقدة بنجاح.",
        'node_updated': "🔄 تم تحديث معلومات العقدة.",

        # SSH validation
        'invalid_ssh_key_format': "❌ تنسيق مفتاح SSH غير صحيح. يجب أن يبدأ المفتاح بـ -----BEGIN",
        'testing_ssh_connection': "🔄 اختبار اتصال SSH...",
        'ssh_test_success': "✅ اختبار اتصال SSH نجح.",
        'ssh_test_failed': "❌ فشل اختبار اتصال SSH: {error}",

        # Bulk installation
        'bulk_auth_choice': "🔐 يرجى اختيار طريقة المصادقة للتثبيت الجماعي:",
        'bulk_password_auth': "🔒 المصادقة القائمة على كلمة المرور",
        'bulk_ssh_key_auth': "🔑 مصادقة مفتاح SSH",
        'bulk_enter_servers_with_password': "📋 يرجى إدخال قائمة الخوادم بالتنسيق التالي (واحد في كل سطر):\nIP USERNAME PASSWORD\nIP USERNAME PASSWORD\n\nمثال:\n192.168.1.1 root mypassword123\n192.168.1.2 admin myotherpass",
        'bulk_enter_servers_for_ssh': "📋 يرجى إدخال قائمة الخوادم بالتنسيق التالي (واحد في كل سطر):\nIP USERNAME\nIP USERNAME\n\nمثال:\n192.168.1.1 root\n192.168.1.2 admin",
        'bulk_enter_ssh_key': "🔑 يرجى إرسال مفتاح SSH الخاص الذي سيتم استخدامه لجميع الخوادم:",
        'enter_server_list': "📋 يرجى إدخال قائمة الخوادم بالتنسيق التالي (واحد في كل سطر):\nIP USERNAME PASSWORD_OR_SSH_KEY\n\nأمثلة:\n192.168.1.1 root mypassword\n192.168.1.2 admin -----BEGIN OPENSSH PRIVATE KEY-----\nMIIEpAIB...\n-----END OPENSSH PRIVATE KEY-----",
        'bulk_auth_method': "🔐 يرجى اختيار طريقة المصادقة للخوادم:",
        'enter_bulk_password': "🔒 يرجى إدخال كلمة المرور المشتركة لجميع الخوادم:",
        'enter_bulk_ssh_key': "🔑 يرجى إرسال مفتاح SSH الخاص لجميع الخوادم:",
        'invalid_server_format': "❌ تنسيق خادم غير صحيح. يرجى إدخال الخوادم بالتنسيق الصحيح.",
        'installing_bulk_nodes': "🚀 تثبيت العقد على خوادم متعددة... قد تستغرق هذه العملية وقتاً كبيراً.",
        'bulk_install_complete': "📊 اكتمل التثبيت الجماعي!\n✅ نجح: {successful}\n❌ فشل: {failed}",
        'network_error': "🌐 خطأ في اتصال الشبكة. يرجى التحقق من اتصالك بالإنترنت.",
        'server_error': "🔧 حدث خطأ في الخادم. يرجى المحاولة لاحقاً.",
        'permission_denied': "🚫 تم رفض الإذن. يرجى التحقق من حقوق الوصول الخاصة بك.",
        'file_not_found': "📁 الملف غير موجود. يرجى التحقق من مسار الملف.",
        'invalid_input': "❌ تم توفير إدخال غير صحيح. يرجى التحقق من بياناتك والمحاولة مرة أخرى.",
        'session_expired': "⏰ انتهت صلاحية جلستك. يرجى البدء من جديد.",
    }
}

# Supported languages list
SUPPORTED_LANGUAGES = ['en', 'fa', 'ru', 'ar']

def get_text(key: str, lang: str = 'en', **kwargs) -> str:
    """Get localized text by key and language"""
    text = TEXTS.get(lang, TEXTS['en']).get(key, TEXTS['en'].get(key, key))
    if kwargs:
        try:
            return text.format(**kwargs)
        except:
            return text
    return text
